app:
  express: 
    httpOnly: true
  server:
    # baseUri: "https://ottonomy.ngrok.io"
    # baseUri: "https://opencred.test:22443"
    # baseUri: https://immensely-fitting-wallaby.ngrok-free.app
    baseUri: https://kezikedb.ngrok.io
  mongodb:
    url: "mongodb://127.0.0.1:27017/opencred"
  opencred:
    caStore:
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIICLjCCAdSgAwIBAgIUXrDPrioY9PCUO5hCXJTsVIZwI0cwCgYIKoZIzj0EAwIw
          UDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNBMQwwCgYDVQQKDANETVYxIzAh
          BgNVBAMMGkNhbGlmb3JuaWEgRE1WIFJvb3QgQ0EgVUFUMB4XDTIzMDQxNDE3MjQ0
          N1oXDTMzMDIyMDE3MjQ0N1owUDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNB
          MQwwCgYDVQQKDANETVYxIzAhBgNVBAMMGkNhbGlmb3JuaWEgRE1WIFJvb3QgQ0Eg
          VUFUMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEORXa3DGvoGS0s6S71Vw5oKEw
          DdPubWyg75A2p1hca4b66MA0LXUWjoz1cIKUJpyEket9ajEx5+hQvB3yvycKVqOB
          izCBiDAdBgNVHQ4EFgQUSWhCfS8C3wEPseC28ScmFn0j25UwEgYDVR0TAQH/BAgw
          BgEB/wIBADALBgNVHQ8EBAMCAQYwHQYDVR0SBBYwFIESZXhhbXBsZUBkbXYuY2Eu
          Z292MCcGA1UdHwQgMB4wHKAaoBiGFmh0dHBzOi8vZG12LmNhLmdvdi9jcmwwCgYI
          KoZIzj0EAwIDSAAwRQIgbpRE08g3aId6e2QULkmlTqnGq0+6kqLltHfjmO6/5MEC
          IQDJdY3WnkpFhPw+Ej3ANlFzwvaDgfaacODGR0pFvBQwlg==
          -----END CERTIFICATE-----
    signingKeys:
      - type: ES256
        privateKeyPem: |
          -----BEGIN PRIVATE KEY-----
          MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgxTZY05ipcV6DffqK
          moFZViLlrQ4hNAvahfaYVtXSleOhRANCAAQCoTePheWxhCLKaIyTc+0YrhLrSn+c
          PtywNPw+W6deCmdA4DeGh0NKNSYfJ9m6srlVTmCrJvItY2YIpAaLPNR9
          -----END PRIVATE KEY-----
        publicKeyPem: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAqE3j4XlsYQiymiMk3PtGK4S60p/
          nD7csDT8PlunXgpnQOA3hodDSjUmHyfZurK5VU5gqybyLWNmCKQGizzUfQ==
          -----END PUBLIC KEY-----
        purpose:
          - id_token
          - authorization_request
    didWeb: 
      mainEnabled: true
      linkageEnabled: true
      # services: 
      #   - id: "https://entraverifiedid.com/tenant/abc123"
      #     type: "https://entraverifiedid.com/VerifiablePresentationService"
      #     serviceEndpoint: 'https://entraverifiedid.com/tenant/abc123/doDidstuff'
    enableAudit: true
    auditFields: 
      - "type": "text"
        "id": "given_name"
        "name": "First Name"
        "path": "$.credentialSubject.driversLicense.given_name"
        "required": true
      - "type": "text"
        "id": "family_name"
        "name": "Last Name"
        "path": "$.credentialSubject.driversLicense.family_name"
        "required": true
      - "type": "date"
        "id": "birth_date"
        "name": "Date of Birth"
        "path": "$.credentialSubject.driversLicense.birth_date"
        "required": true
      - "type": "dropdown"
        "id": "sex"
        "name": "Sex"
        "path": "$.credentialSubject.driversLicense.sex"
        "required": false
        "options": 
            "Male": 1
            "Female": 2
            "Not Known": 0
            "Not Applicable": 9  
      - "type": "dropdown"
        "id": "aamva_veteran"
        "name": "Are you a veteran?"
        "path": "$.credentialSubject.driversLicense.aamva_veteran"
        "required": false
        "options": 
            "Yes": 1,
            "No": null
      - "type": "text"
        "id": "issuing_authority"
        "name": "Issuing Authority"
        "path": "$.credentialSubject.driversLicense.issuing_authority"
        "required": false
      - "type": "text"
        "id": "document_number"
        "name": "DL/ID Number"
        "path": "$.credentialSubject.driversLicense.document_number"
        "required": true
      - "type": "dropdown"
        "id": "aamva_dhs_compliance"
        "name": "REAL ID Compliance"
        "path": "$.credentialSubject.driversLicense.aamva_dhs_compliance"
        "required": false
        "options":
            "Fully Compliant": Y
            "Non-Compliant": N
      - "type": "date"
        "id": "issue_date"
        "name": "Issue Date"
        "path": "$.credentialSubject.driversLicense.issue_date"
        "required": true
      - "type": "date"
        "id": "expiry_date"
        "name": "Expiry Date"
        "path": "$.credentialSubject.driversLicense.expiry_date"
        "required": true
    relyingParties:
      - name: "Cat App"
        clientId: "cats"
        clientSecret: "CavesOfFurryFury"
        description: "Relying Party App for Cats"
        icon: "https://loremflickr.com/300/80"
        backgroundImage: "https://loremflickr.com/800/300"
        brand:
          cta: "#8A2BE2"
          primary: "#6A5ACD"
          header: "#9370DB"
        redirectUri: "https://openidconnect.net/callback"
        scopes:
          - name: "openid"
            description: Open Id Connect is a lorem ipsum dolor sit amet. Dollars to donuts this is a very long description that will wrap around and around and around. 
        workflow: 
          type: native
          id: catappworkflow
          initialStep: default
          steps:
            default:
              createChallenge: true
              verifiablePresentationRequest: >
                {
                  "query": {
                    "type": "QueryByExample",
                    "credentialQuery": {
                      "reason": "Please present your Driver's License to complete the verification process.",
                      "example": {
                        "@context": [
                          "https://www.w3.org/2018/credentials/v1",
                          "https://w3id.org/vdl/v1",
                          "https://w3id.org/vdl/aamva/v1"
                        ],
                        "type": [
                          "Iso18013DriversLicenseCredential"
                        ]
                      }
                    }
                  }
                }
        claims:
          - name: "email"
            sourcePath: "driversLicense.document_number"
        translations:
          en: 
            loginCta: "Login with your Cat Pass"
            loginExplain: To login with your Cat Pass, you will need to have the Cat Pass App installed.
            appInstallExplain: If you don't have a Cat Pass yet, you can get one by downloading the <a href="https://example.com">Cat Pass app</a>.
            appCta: "Open Cat Pass"
            qrExplain: "Looking for a QR Code to scan with you Cat Pass App instead?"
            qrPageExplain: "Scan the following QR Code with your Cat Pass App."
            qrPageCta: 'Scan QR Code from within your digital wallet app.'
            copyright: "Copyright &copy; 2023 Herd of Cats"
      - name: California DMV
        clientId: "dmv"
        clientSecret: "DriveLikeTheWind"
        description: "California DMV"
        icon: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/241cb0c9-d92c-40b7-1745-6d5e68a45d00/public"
        backgroundImage: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/f7516576-f9d3-4a15-1b9e-e95281613700/public"
        brand:
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        redirectUri: "http://localhost:3000"
        explainerVideo:
          provider: "youtube"
          id: "dQw4w9WgXcQ"
        scopes:
          - name: "openid"
            description: "Open ID Connect"
        workflow: 
          type: native
          id: dmvappworkflow
          initialStep: default
          steps:
            default:
              createChallenge: true
              verifiablePresentationRequest: >
                {
                  "query": {
                    "type": "QueryByExample",
                    "credentialQuery": {
                      "reason": "Please present your Driver's License to complete the verification process.",
                      "example": {
                        "@context": [
                          "https://www.w3.org/2018/credentials/v1",
                          "https://w3id.org/vdl/v1",
                          "https://w3id.org/vdl/aamva/v1"
                        ],
                        "type": [
                          "Iso18013DriversLicenseCredential"
                        ]
                      }
                    }
                  }
                }
              constraintsOverride: >
                {
                  "fields": [
                    {
                      "path": [
                        "$.vc.type"
                      ],
                      "filter": {
                        "type": "string",
                        "pattern": "Iso18013DriversLicenseCredential"
                      }
                    }
                  ]
                }
        claims:
          - name: "email"
            path: "email"
        translations:
          en: 
            loginCta: "Login with your Digital Driver's License"
            loginExplain: To login with your California Digital Driver's License, you will need to have the California Driver's License App installed.
            appInstallExplain: If you don't have a digital driver's license yet, you can get one by downloading the <a href="https://example.com">California Driver's License App</a>
            appCta: "Open CA DMV App"
            qrExplain: "Looking for a QR Code to scan with you California Driver's License App instead?"
            qrExplainerText: "Having trouble with this dance? Learn the moves."
            qrPageExplain: "Scan the following QR Code with your California Driver's License App."
            qrPageExplainHelp: ''
            qrPageCta: 'Scan QR Code from within your digital wallet app.'
            copyright: "Copyright &copy; 2023 State of California"
      - name: "load-test"
        clientId: "load-test"
        clientSecret: "DeepestAndDarkest"
        description: "Load Testing Profile"
        icon: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/241cb0c9-d92c-40b7-1745-6d5e68a45d00/public"
        backgroundImage: "https://imagedelivery.net/I-hc6FAYxquPgv-npvTcWQ/f7516576-f9d3-4a15-1b9e-e95281613700/public"
        redirectUri: "http://localhost:3000"
        idTokenExpirySeconds: 3600
        claims:
          - name: "dl_number"
            path: "driversLicense.document_number"
        brand:
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        scopes:
          - name: "openid"
            description: "Open ID Connect"
        workflow:
          type: native
          id: load-test
          initialStep: default
          steps:
            default:
              createChallenge: true
              verifiablePresentationRequest: >
                {
                  "query": {
                    "type": "QueryByExample",
                    "credentialQuery": {
                      "reason": "Please present your VC.",
                      "example": {
                        "type": [
                          "DomainLinkageCredential"
                        ]
                      }
                    }
                  }
                }
              constraintsOverride: >
                {
                  "fields": [
                    {
                      "path": [
                        "$.vc.type"
                      ],
                      "filter": {
                        "type": "string",
                        "pattern": "DomainLinkageCredential"
                      }
                    }
                  ]
                }
      - name: "Oxhead Alpha Vehicle Title System"
        configFrom: "load-test"
        clientId: "oxhead"
        clientSecret: "oxhead_secret"
        description: "A credentials-based vehicle titling system in partnership with California DMV"
        redirectUri: "https://openidconnect.net/callback"
        workflow:
          type: native
          id: "z19mLsUzMweuIUlk349cpekAz"
          initialStep: default
          steps:
            default:
              createChallenge: true
              verifiablePresentationRequest: >
                {
                  "query": {
                    "type": "QueryByExample",
                    "credentialQuery": {
                      "reason": "Please present your Driver's License to complete the verification process.",
                      "example": {
                        "@context": [
                          "https://www.w3.org/2018/credentials/v1",
                          "https://w3id.org/vdl/v1",
                          "https://w3id.org/vdl/aamva/v1"
                        ],
                        "type": [
                          "Iso18013DriversLicenseCredential"
                        ]
                      }
                    }
                  },
                  "domain": "https://${bedrock_host}"
                }
              constraintsOverride: >
                {
                  "fields": [
                    {
                      "path": [
                        "$.vc.type"
                      ],
                      "filter": {
                        "type": "string",
                        "pattern": "Iso18013DriversLicenseCredential"
                      }
                    }
                  ]
                }
    options:
      exchangeProtocols: 
        - chapi
        - openid4vp
    defaultLanguage: en
    defaultBrand:
      cta: "#0B669D"
      primary: "#045199"
      header: "#0979c4"
    translations:
      en:
        loginCta: "Login with your Cat Fan Club credential"
        loginExplain: To login, you will need to have a Verifiable Credentials wallet installed.
        appInstallExplain: "Scoot off to yer app store now."
        appCta: "Open CA DMV App"
        appCta-chapi-label: "Open Wallet (via CHAPI)"
        appCta-openid4vp-label: "Open Wallet on this device (via OID4VP)"
        chapiPageAnotherWay: "Try another way."
        qrExplain: "Need a different way to connect to your wallet?"
        qrPageExplain: "Scan QR Code from within your OID4VP-enabled digital wallet app."
        qrPageCta: "Scan the following QR Code with your wallet app."
        qrPageAnotherWay: "Try another way"
        qrDisclaimer: We disclaim all oddities in processing this QR code. Call somebody else!
        copyright: "Provided by 2024 Cat World Incorporated LLC Forever"
